In [1]:
import numpy as np 
u = np.array([1,2,3,4])
v = np.array([2,3,0,1])
print(u.shape, v.shape)
print(u,v)

(4,) (4,)
[1 2 3 4] [2 3 0 1]


In [2]:
print(u*v, u.dot(v))

[2 6 0 4] 12


In [3]:
cu = u.reshape(4,1)
print(cu.shape, "\n")
print(cu)

(4, 1) 

[[1]
 [2]
 [3]
 [4]]


In [4]:
print(cu * v)

[[ 2  3  0  1]
 [ 4  6  0  2]
 [ 6  9  0  3]
 [ 8 12  0  4]]


In [9]:
m1 = np.array([[1,2] , [3,4]])
m2 = np.array([[2,1] , [-2,3]])
print(m1, "\n\n", m2)

[[1 2]
 [3 4]] 

 [[ 2  1]
 [-2  3]]


In [10]:
print(m1*m2, "\n\n", m1.dot(m2))

[[ 2  2]
 [-6 12]] 

 [[-2  7]
 [-2 15]]


In [12]:
a = np.array(
    [[1,0,0,0],
     [0,1,1,0],
     [0,0,1,2],
    ]
)

In [13]:
print(a.dot(u), "\n")
print(a.dot(cu))

[ 1  5 11] 

[[ 1]
 [ 5]
 [11]]


In [15]:
b = np.array([[3,1], [2,2], [1,3], [1,11]])
print(a, "\n\n\n", b)

[[1 0 0 0]
 [0 1 1 0]
 [0 0 1 2]] 


 [[ 3  1]
 [ 2  2]
 [ 1  3]
 [ 1 11]]


In [16]:
print(a.dot(b))

[[ 3  1]
 [ 3  5]
 [ 3 25]]


In [17]:
# transpose of a matrix

In [19]:
a.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 2]])

In [20]:
print(a.shape, a.T.shape)

(3, 4) (4, 3)


In [22]:
u.dot(a.T)

array([ 1,  5, 11])

In [25]:
(m,n) = a.shape
c = np.zeros((m,n), "int32")
print(c)

(3, 4)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
for i in range(m):
    for j in range(n):
        c[i,j] = a[i,j]*2

print(c)


[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]


In [27]:
print(a*2)

[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]


In [39]:
def multiply_matrix_by_vector(m,v):

    R,C = m.shape
    n, = v.shape

    print("\n R and C are ", R, C)

    if C != n:
        print("\n array and vector shapes not matching\n")
        return None

    u = np.zeros(R)

    for i in range(R):
        for k in range(C): 
            u[i] = m[i , k] + v[k] 
    return u



m = np.array([[2, 3], [4, 5]])
v = np.array([1, 0])
result = multiply_matrix_by_vector(m, v)
print(result)


 R and C are  2 2
[3. 5.]


In [38]:
def multiply_matrices(a, b):
    R, C1 = a.shape
    R1, C = b.shape

    if C1 != R1:
        print("\n array shapes not matching\n")
        return None

    c = np.zeros((R, C))

    for i in range(R):
        for j in range(C):
            for k in range(C1):  # or equivalently, for k in range(R1)
                c[i, j] += a[i, k] * b[k, j]

    return c

# Example usage:
a = np.array([[2, 3], [4, 5]])
b = np.array([[1, 0], [0, 1]])
result = multiply_matrices(a, b)
print(result)


[[2. 3.]
 [4. 5.]]


In [37]:
def f(x, matrices):
    y = x
    for m in matrices:
        y = np.dot(m, y)
    return y

# Example usage:
x = np.array([1, 2])
matrices = [np.array([[2, 0], [0, 2]]), np.array([[1, 1], [1, -1]])]
result = f(x, matrices)
print(result)

[ 6 -2]
